from sqlalchemy import BigInteger, Boolean, Integer, VARCHAR, TIMESTAMP, SMALLINT
from sqlalchemy import ForeignKey, create_engine, Table, MetaData, Column
from sqlalchemy.orm import sessionmaker
from sqlalchemy.dialects.postgresql import JSONB
from d2preparer.envvar import db_host, db_name, db_pass, db_port, db_user

engine = create_engine(f'postgresql+psycopg2://{db_user}:{db_pass}@{db_host}:{db_port}/{db_name}')

Session = sessionmaker(bind=engine)

conn = engine.connect()

metadata = MetaData()

public_match = Table(
    'public_match',
    metadata,
    Column('match_pk', BigInteger, primary_key=True),
    Column('match_seq_num', BigInteger, nullable=False),
    Column('radiant_win', Boolean, nullable=False),
    Column('duration', Integer),
    Column('avg_mmr', Integer),
    Column('game_mode', Integer),
    Column('radiant_team', VARCHAR(25)),
    Column('dire_team', VARCHAR(25))
)

pro_match = Table(
    'pro_match',
    metadata,
    Column('match_pk', BigInteger, primary_key=True),
    Column('match_seq_num', Integer),
    Column('radiant_win', Boolean),
    Column('duration', Integer),
    Column('game_mode', Integer),
    Column('radiant_team_id', Integer),
    Column('radiant_name', VARCHAR(255)),
    Column('dire_team_id', Integer),
    Column('dire_name', VARCHAR(255)),
    Column('radiant_score', Integer),
    Column('dire_score', Integer),
    Column('radiant_team', VARCHAR(25)),
    Column('dire_team', VARCHAR(25)),
    Column('radiant_team_bans', VARCHAR(25)),
    Column('dire_team_bans', VARCHAR(25)),
    Column('first_blood_time', Integer),
    Column('human_players', Integer),
    Column('start_time', Integer),
    Column('replay_url', VARCHAR(255)),
    Column('downloaded_replay', Boolean),
    Column('parse_success', Boolean),
    Column('hero0', Integer),
    Column('hero1', Integer),
    Column('hero2', Integer),
    Column('hero3', Integer),
    Column('hero4', Integer),
    Column('hero5', Integer),
    Column('hero6', Integer),
    Column('hero7', Integer),
    Column('hero8', Integer),
    Column('hero9', Integer)
)

pro_match_details = Table(
    'pro_match_details',
    metadata,
    Column('match_details_pk', BigInteger, primary_key=True),
    Column('match_pk', BigInteger, ForeignKey(pro_match.c.match_pk)),
    Column('gold0', Integer),
    Column('gold1', Integer),
    Column('gold2', Integer),
    Column('gold3', Integer),
    Column('gold4', Integer),
    Column('gold5', Integer),
    Column('gold6', Integer),
    Column('gold7', Integer),
    Column('gold8', Integer),
    Column('gold9', Integer),
    Column('xp0', Integer),
    Column('xp1', Integer),
    Column('xp2', Integer),
    Column('xp3', Integer),
    Column('xp4', Integer),
    Column('xp5', Integer),
    Column('xp6', Integer),
    Column('xp7', Integer),
    Column('xp8', Integer),
    Column('xp9', Integer),
    Column('last_hits0', SMALLINT),
    Column('last_hits1', SMALLINT),
    Column('last_hits2', SMALLINT),
    Column('last_hits3', SMALLINT),
    Column('last_hits4', SMALLINT),
    Column('last_hits5', SMALLINT),
    Column('last_hits6', SMALLINT),
    Column('last_hits7', SMALLINT),
    Column('last_hits8', SMALLINT),
    Column('last_hits9', SMALLINT),
    Column('level0', SMALLINT),
    Column('level1', SMALLINT),
    Column('level2', SMALLINT),
    Column('level3', SMALLINT),
    Column('level4', SMALLINT),
    Column('level5', SMALLINT),
    Column('level6', SMALLINT),
    Column('level7', SMALLINT),
    Column('level8', SMALLINT),
    Column('level9', SMALLINT),
    Column('kills0', SMALLINT),
    Column('kills1', SMALLINT),
    Column('kills2', SMALLINT),
    Column('kills3', SMALLINT),
    Column('kills4', SMALLINT),
    Column('kills5', SMALLINT),
    Column('kills6', SMALLINT),
    Column('kills7', SMALLINT),
    Column('kills8', SMALLINT),
    Column('kills9', SMALLINT),
    Column('deaths0', SMALLINT),
    Column('deaths1', SMALLINT),
    Column('deaths2', SMALLINT),
    Column('deaths3', SMALLINT),
    Column('deaths4', SMALLINT),
    Column('deaths5', SMALLINT),
    Column('deaths6', SMALLINT),
    Column('deaths7', SMALLINT),
    Column('deaths8', SMALLINT),
    Column('deaths9', SMALLINT),
    Column('assists0', SMALLINT),
    Column('assists1', SMALLINT),
    Column('assists2', SMALLINT),
    Column('assists3', SMALLINT),
    Column('assists4', SMALLINT),
    Column('assists5', SMALLINT),
    Column('assists6', SMALLINT),
    Column('assists7', SMALLINT),
    Column('assists8', SMALLINT),
    Column('assists9', SMALLINT),
    Column('denies0', SMALLINT),
    Column('denies1', SMALLINT),
    Column('denies2', SMALLINT),
    Column('denies3', SMALLINT),
    Column('denies4', SMALLINT),
    Column('denies5', SMALLINT),
    Column('denies6', SMALLINT),
    Column('denies7', SMALLINT),
    Column('denies8', SMALLINT),
    Column('denies9', SMALLINT),
    Column('rt1t', Boolean),
    Column('rt2t', Boolean),
    Column('rt3t', Boolean),
    Column('rt1m', Boolean),
    Column('rt2m', Boolean),
    Column('rt3m', Boolean),
    Column('rt1b', Boolean),
    Column('rt2b', Boolean),
    Column('rt3b', Boolean),
    Column('r_rosh', SMALLINT),
    Column('dt1t', Boolean),
    Column('dt2t', Boolean),
    Column('dt3t', Boolean),
    Column('dt1m', Boolean),
    Column('dt2m', Boolean),
    Column('dt3m', Boolean),
    Column('dt1b', Boolean),
    Column('dt2b', Boolean),
    Column('dt3b', Boolean),
    Column('d_rosh', SMALLINT),
    Column('time_part', SMALLINT)
)

error_log = Table(
    'error_log',
    metadata,
    Column('error_log_pk', BigInteger, primary_key=True),
    Column('error_message', JSONB, nullable=False),
    Column('module_name', VARCHAR(255), nullable=False),
    Column('date_creation', TIMESTAMP)
)
